# whocontributes 07/04/2019
# pulled from https://wiki.mabinogiworld.com/index.php?title=Special:WhatLinksHere/Template:StyleMonster&namespace=0&limit=500
FAMILY_PAGES_LIST = ['Aardvarks', 'Alchemists (Enemy)', 'Alligators', 'Angry Bear', 'Ant Lions', 'Aonbharrs',
					 'Argus (Family)', 'Armadillos', 'Balrogs', 'Bandersnatch (Family)', 'Banshees', 'Bison',
					 'Boar (Family)', 'Booby (NPC)', 'Buffalo', 'Bunting (NPC)', 'Butterfly', 'Carnivorous Plant',
					 'Castle Warrior', 'Cat', 'Cat (NPC)', 'Cat Humanoid', 'Chess Piece', 'Chicken (NPC)',
					 'Cloaker (Family)', 'Cobra', 'Cor Villagers', 'Cotton Candy Sheep (Event)', 'Cow (NPC)',
					 'Coyote (Family)', 'Crab', 'Crow (NPC)', 'Cyclops (Family)', 'Dark Lord', 'Deer (Monster)',
					 'Deer (NPC)', 'Desert Ghost', 'Dingo (Family)', 'Dog (Family)', 'Dog (NPC)', 'Dragon',
					 'Dragonfly (Family)', 'Dullahan (Family)', 'Elephant', 'Elf Archer', 'Esras (Monster)',
					 'Event Monsters', 'Event Monsters/Constellation Event', 'Event Monsters/Cookie Island Event',
					 "Event Monsters/Lorraine's Nightmare Event", 'Event Monsters/Spirit Caravan Event', 'Fox',
					 'Ghast (Family)', 'Ghost', 'Giant Guard (Family)', 'Giant Headless (Family)', 'Giant Knight',
					 'Giant Moon Bunny (Event)', 'Glas Ghaibhleann (Family)', 'Gnoll', 'Gnu', 'Goat (NPC)',
					 'Gorgon (Family)', 'Grendel', 'Guardian of Ruins (Family)', 'Hedgehog (NPC)', 'Hobgoblin',
					 'Hornet', 'Horse', 'Horse (NPC)', 'Hyena', 'Ice Bear', 'Ice Worm (NPC)', 'Ifrit (Family)',
					 'Iguana (NPC)', 'Incubus (Family)', 'Ixion', 'Jackal (Family)', 'Jewel Beetle', 'Kiwi',
					 'Laghodessa', 'Larva', 'Lebbaeus (Monster)', 'Leopard', 'Lich', 'Lion (Family)', 'Living Armor',
					 'Lizard', 'Llama', 'Lucas (Monster)', 'Lungfish (Family)', 'Lynx', 'Mask', 'Millipede',
					 'Mini Milk Cow (Event)', 'Mongoose', 'Monkey (NPC)', 'Moth', 'Mouse', 'Neid (Family)',
					 'Nightmare Humanoid (Family)', 'Ostrich', 'Ostrich (NPC)', 'Otter (NPC)', 'Penguin',
					 'Pigeon (NPC)', 'Porcupine', 'Pot-Belly Spider (Family)', 'Python', 'Rabbit', 'Rabbit (NPC)',
					 'Raptor', 'Rhino', 'Ruairi (Monster)', 'Sahagin', 'Sarracenia', 'Scorpion', 'Sheep (Family)',
					 'Sheep (NPC)', 'Shrieker (Family)', 'Siren (Monster)', 'Skelemancer', 'Skeleton (Hard Mode)',
					 'Skeleton Wolf (Family)', 'Slate', 'Soldier Knight', 'Specter Army', 'Spider Humanoid',
					 'Spirit of Jabchiel', 'Sprite', 'Stag Beetle', 'Stone Gargoyle (Family)', 'Stone Horse',
					 'Stone Hound (Family)', 'Stone Imp (Family)', 'Stone Zombie (Family)', 'Succubus Kristell',
					 'Tarantula', 'Temple Knight', 'Training Monsters', 'Triona (Monster)', 'Warg', 'Wasp', 'Witch',
					 'Worm', 'Wyvern', 'Yeti (Family)', 'Zebra (NPC)', 'Zombie (Family)']

GM_LIST = ['(Amateur Conqueror) Black Knight', '(Amateur Druid) Berched', '(Amateur Repairer) Jennifer',
		   '(Amateur Student) Lassar', '(Amateur Warlord) Andras', '(Amateur Warrior) Trefor',
		   '(Apprentice Addicted Archer) Granites', '(Apprentice Bard) Nele', '(Apprentice Commander) Tethra',
		   '(Apprentice Holy Knight) Collen', '(Apprentice Holy Knight) Secretive Knightage',
		   '(Apprentice Home Economist) Taunes', '(Apprentice Mage) Galvin',
		   '(Apprentice Sailor) Admiral Owen', '(Apprentice Sharp Shooter) Riocard',
		   '(Apprentice Troubadour) Sinead', '(Apprentice Warrior in Crush) Padan',
		   '(Champion Fighter) Giant Fighter', '(Fledgling Battle Alchemist) Heledd',
		   '(Fledgling Blacksmith) Ferghus', '(Master Addicted Archer) Annick',
		   '(Master Addicted Swordsman) Lucas', '(Master Alchemist) Dorren', '(Master Archer) Granat',
		   '(Master Battle Alchemist) Eabha', '(Master Battle Alchemist) Heledd', '(Master Blacksmith) Edern',
		   '(Master Brawler) Cecilia', '(Master Cleric) Comgan', '(Master Dog Fighter) Fleta',
		   '(Master Druid) Tarlach', '(Master Executioner) Krug', '(Master Fighter) Argel',
		   '(Master Gourmet) Beggar', '(Master Maid) Older Girl Next Door', '(Master Marksman) Drone',
		   '(Master Musician) Briana', '(Master Orfevre) Walter', '(Master Ranger) Waboka',
		   '(Master Romantic Chef) Glewyas', '(Master Shaman) Kousai', '(Master Shepherd Fighter) Deian',
		   '(Master Tailor) Simon', '(Master Vagabond) Price', '(Master Vanguard) Lileas',
		   '(Master Warrior) Aodhan', '(Master of Reading) Arzhela', '(Master of the Beasts) Ruwai',
		   '(Master of the Single Life) Bryce', '(Seasoned Cleric) Agnes', '(Seasoned Flower Merchant) Del',
		   '(Senior Vanguard) Nerys', '(Skilled Mage) Stewart', '(Skilled Minor) Sion',
		   '(Skilled Vanguard) Aranwen', '(Wise Fighter) Goblin Fighter',
		   '(Wise Musical Child Prodigy) Goblin Bard']
# pulled from https://wiki.mabinogiworld.com/view/Property:Monster_skills
VALID_SKILLS = ["Abyss Judgement", "Abyss Snare", "Abyss Terror", "Act 1: Inciting Incident", "Act 2: Threshold Cutter",
				"Act 4: Rising Action", "Act 6: Crisis", "Act 7: Climactic Crash", "Act 9: Invigorating Encore",
				"Actions", "Advanced Heavy Stander", "Alban Golem Ambush", "Alban Golem Gatling",
				"Alban Golem Ice Slip", "Alchemy Mastery", "Anchor Rush", "Armor of Connous", "Arrow Revolver",
				"Artifact Investigation", "Assault Slash", "Awakening of Light", "Axe Mastery", "Axe Throwing",
				"Bachram Explosion", "Barrier Spikes", "Bash", "Battlefield Overture", "Beast", "Beast Roar",
				"Beholder Beam Attack", "Berserk", "Bewilder", "Binding Needle", "Black Dragon's Breath",
				"Blacksmithing", "Blaze", "Blink", "Blunt Mastery", "Body of Chaos", "Bolt Mastery",
				"Bolt Out of the Blue (Monster)", "Boost", "Bow Mastery", "Bran's Arm Swing", "Bran's Charge",
				"Bran's Shockwave", "Breaking Lies", "Breath of Ladeca", "Bubble Blast", "Bullet Slide", "Bullet Storm",
				"Burnout", "Campfire", "Carpentry", "Catering", "Celestial Spike", "Chain Blade Mastery", "Chain Burst",
				"Chain Casting (Monster)", "Chain Crush", "Chain Cylinder", "Chain Impale", "Chain Sweep", "Charge",
				"Charge (Pet)", "Charging Strike", "Christening Blades", "Cleansing Dust",
				"Close-quarters Sandworm Attack", "Colossus Marionette", "Combat Mastery", "Combo Mastery",
				"Combo: Counter Punch", "Commerce Mastery", "Compose", "Connous Heavy Stander",
				"Connous Mana Deflector", "Connous Natural Shield", "Control Marionette", "Control of Darkness",
				"Cooking", "Counterattack", "Crash Shot", "Create Falias Portal", "Crisis Escape", "Critical Hit",
				"Crossbow Mastery", "Curse of Devil", "Daemon of Physis", "Dance Time", "Dance of Death",
				"Dark Heavy Stander", "Dark Knight", "Dark Knight Quest", "Dark Mana Deflector", "Dark Natural Shield",
				"Death Mark", "Deepening Trust", "Defense", "Demigod", "Detection", "Devil's Cry", "Devil's Dash",
				"Dischord", "Divine Blast", "Divine Liberty", "Divine Link", "Divinity", "Doppelganger", "Dorcha",
				"Dorcha Conversion", "Dorcha Mastery", "Dorcha Snatch", "Double-Edged Swing", "Dragon Fireball",
				"Dragon Rage", "Drop Kick", "Dual Gun Mastery", "Dual Wield Mastery", "Duke's Kiss", "Duke's Mist",
				"Duke's Rose", "Duke's Temptation", "Earth Alchemy Mastery", "Earth Dragon Roar", "Egg Gathering",
				"Elemental Wave", "Elf Ranged Attack", "Elven Magic Missile", "Enchant", "Encore", "Enduring Melody",
				"Enlightened Vision", "Enthralling Performance", "Enuma Elish", "Evasion", "Excalibur",
				"Exploration Mastery", "Explosive Kunai", "Eye of Order", "Falcon", "Fanaticism", "Fantastic Chorus",
				"Fast Regeneration", "Fierce Charge", "Final Hit", "Final Shot", "Final Strike", "Fire Alchemy",
				"Fire Breath", "Fire Mastery", "Fire Shield", "Fire Storm", "Fireball", "Firebolt", "First Aid",
				"Fishing", "Flame Burst", "Flame Dive", "Flame of Resurrection", "Flames of Hell", "Flash Launcher",
				"Flight (Monster Skill)", "Focused Fist", "Fragmentation", "Freeze! Stop Right There!", "Frost Blade",
				"Frozen Blast", "Fury of Connous", "Fury of Light", "Fusion Bolt", "Gathering", "Generation 2: Paladin",
				"Ghost Voice", "Giant Full Swing", "Giving Heart", "Glas Ghaibhleann Skill", "God Hand: Twelve Labors",
				"Gold Strike", "Golden Time", "Grapple Shot", "Grim Reaper Horizontal Attack",
				"Grim Reaper Vertical Attack", "Grim Reaper Windmill", "Grudge of Tuan", "Guard Cylinder Mastery",
				"Guarded Footsteps", "Guardian Oath", "Hail Storm", "Handicraft", "Hands of Chaos",
				"Hands of Salvation", "Harvest Song", "Harvesting", "Healing", "Healing Breeze", "Healing Hands",
				"Healing Wind", "Heat Buster", "Heavy Armor Mastery", "Heavy Stander", "Herbalism",
				"Hillwen Engineering", "Hoeing", "Holy Confinement", "Holy Contagion", "Holy Rampage", "Holy Rush",
				"Holy Shower", "Holy Vitality", "Hop In", "Hop Shield", "Hop Spin", "Human Ranged Attack",
				"Hydra Transmutation", "Ice Breath", "Ice Hold", "Ice Mastery", "Ice Shield", "Ice Spear", "Ice Storm",
				"Icebolt", "Ingredient Hunting", "Inspiration", "Instinctive Reaction", "Invisible Air",
				"Invitation of Death", "Invulnerability", "Jack's Frozen Field", "Jack's Garden",
				"Jack's Throw Snowball", "Judgment Blade", "Jump", "King's Treasure", "Knuckle Mastery",
				"Kokopo Strike", "Kokopo Wave", "Kunai Storm", "Lance Charge", "Lance Counter", "Lance Mastery",
				"Life Drain", "Life Drain (Monster)", "Life of Physis", "Light Armor Mastery", "Light of Sword",
				"Lightning Bolt", "Lightning Breath", "Lightning Mastery", "Lightning Rod", "Lightning Shield",
				"Lost and Found (Skill)", "Lullaby", "Magic Craft", "Magic Dampening", "Magic Fusion", "Magic Mastery",
				"Magic Weapon Mastery", "Magnum Shot", "Mana Crystallization", "Mana Deflector", "Mana Drain",
				"Mana Shield", "March Song", "Master Teleport", "Meditation", "Merrow Rising Dragon",
				"Merrow Tidal Wave", "Metal Conversion", "Metallurgy", "Meteor", "Meteor Strike", "Might of Ladeca",
				"Milking", "Mind of Chaos", "Mind of Connous", "Mineral Explosion", "Mineral Hail", "Mini Jack",
				"Mining", "Mirage Missile", "Mushroom Gathering", "Musical Knowledge", "Nascent Divinity",
				"Natural Shield", "Natural Shield (Monster)", "Night Change", "Nova Obliteration", "Paladin",
				"Paladin Heavy Stander", "Paladin Mana Deflector", "Paladin Natural Shield", "Palalan Embrace",
				"Paper Airplane Bomb", "Party Healing", "Passive Defense", "Pet Teleport", "Petrification",
				"Petrifying Roar", "Phantom Roar", "Physis Heavy Stander", "Physis Mana Deflector",
				"Physis Natural Shield", "Pierrot Marionette", "Playing Instrument", "Poison Attack", "Potion Making",
				"Power of Order", "Produce Cobweb", "Production Mastery", "Pummel", "Puppet's Snare", "Purgatory",
				"Rage Impact", "Raging Spike", "Rain Casting", "Rain of Thunder", "Rare Mineralogy", "Recovering Touch",
				"Red Dragon Fire Breath", "Refining", "Reflective Damage", "Reload", "Respite", "Rest", "Restful Wind",
				"Roar", "Roar (Monster)", "Running Boost", "Sacred Revival", "Sakura Abyss", "Sand Burst",
				"Save Location", "Scarecrow Curse", "Self-Destruct", "Shadow Bind", "Shadow Cloak", "Shadow Death",
				"Shadow Spirit", "Sharp Mind", "Sharpness of Connous", "Sheep Shearing", "Shield Mastery",
				"Shield of Physis", "Shield of Trust", "Shine of Eweca", "Shock", "Shockwave", "Shooting Rush",
				"Shuriken Charge", "Shuriken Mastery", "Shyllien Ecology", "Sinful Thorns", "Skills List (Elf)",
				"Skills List (Giant)", "Skills List (Human)", "Sleepy Dust", "Smack", "Smash", "Smokescreen",
				"Snap Cast", "Snow Bomb", "Somersault Kick", "Song", "Soul Absorption", "Soul Chase",
				"Soul Restoration", "Soul of Chaos", "Spear of Light", "Spell of Physis", "Spellwalk", "Spider Shot",
				"Spinning Slash", "Spinning Slasher", "Spinning Uppercut", "Spirit Weapon Awakening", "Spirit of Order",
				"Spreading Faith", "Staff Swing", "Stampede", "Stats and Skills", "Stomp", "Stomp (Monster)",
				"Stronger Power", "Study: Potion Lore", "Summon Golem", "Summon Monster", "Support Shot", "Swallow",
				"Sword Mastery", "Sword of Order", "Synthesis", "Tail Attack", "Tailoring", "Taming Wild Animals",
				"Tasting", "Taunt", "Teleportation", "The Fake Spiral Sword", "Throwing Attack", "Thunder",
				"Thunder Breath", "Thunder Storm", "Tiny Jibes", "Transformation Mastery", "Transformations",
				"Transmutation", "Trial of Pain", "Truck to the Head", "Tumble", "Unlimited Blade Works", "Urgent Shot",
				"Vision of Ladeca", "Vivace", "Water Alchemy", "Water Cannon", "Water Spray", "Way of the Gun",
				"Weaving", "Weighed Conscience", "Whisper of Tuan", "White Dragon's Breath", "Wind Alchemy",
				"Wind Blast", "Wind Guard", "Windmill", "Wine Making", "Wings of Eclipse", "Wings of Rage", "Wire Pull",
				"Wool of the Gods", "Wounding Soul"]
SKILL_BLACKLIST = ['HeavyStander', 'ManaDeflector', 'NaturalShield', 'None']
CAPITIAL_EACH_WORD = ["Speed", "Element", "AggroRange", "AggroSpeed"]
NUMERICAL_VALUES = ["ExplosiveDamage", "HP", "CP", "Defense", "Protection", "Crit", "EXP"]
BALTANE_MISSIONS = ["Avalon Bridge", "Nowhere to Run", "Knights of the Round Table", "Gatekeeper",
					"Counterattack (Baltane Mission)", "Siege Weapon"]
THEATRE_MISSIONS = ["The New King's Request", "Guardian of Avon", "Fortinbras's Expedition", "Warden of the Gods",
					"Erinn Martial Arts"]
SPEED = ["Very Slow", "Slow", "Medium", "Fast", "Very Fast", "Immobile", ""]
AGGRO_SPEED = ["Very Slow", "Slow", "Medium", "Fast", "Very Fast", "Instant", "None", ""]
AGGRO_RANGE = ["Very Small", "Small", "Medium", "Far", "Very Far", "Extremely Far", "None", ""]
MULTI_AGGRO = ["n", "y", "1", "2", "3", "4", "5"]
ELEMENT = ["Fire", "Lightning", "Ice", "None"]
